spring:
  application:
    name:epos-ai-assistant

server:
  port: 8080

langchain4j:
  community:
    dashscope:
      chat-model:
        model-name: qwen-plus
        api-key: <your key>
      embedding-model:
        model-name: text-embedding-v4
        api-key: <your key>
      streaming-chat-model:
        model-name: qwen-plus
        api-key: <your key>
